// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfferGen.Repository;

#nullable disable

namespace OfferGen.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241008141311_CLientModelAndConfiguration")]
    partial class CLientModelAndConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfferGen.Entities.Models.Clients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaxIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_RegistrationNumber");

                    b.HasIndex("TaxIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_TaxIdentifier");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaxIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_RegistrationNumber");

                    b.HasIndex("TaxIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_Company_TaxIdentifier");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.CompanyRelations.BankAccounts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BankAccountId")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_BankAccounts_CompanyId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.CompanyRelations.OfferHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OfferHeaderId");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderCaption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_OfferHeader_CompanyId");

                    b.ToTable("OfferHeader");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.Clients", b =>
                {
                    b.OwnsOne("OfferGen.Entities.Records.ComplexValueTypes+Address", "ClientAddress", b1 =>
                        {
                            b1.Property<Guid>("ClientsId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZIPCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientsId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientsId");
                        });

                    b.OwnsOne("OfferGen.Entities.Records.ComplexValueTypes+ContactInfo", "ClientContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ClientsId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContactPerson")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientsId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientsId");
                        });

                    b.Navigation("ClientAddress")
                        .IsRequired();

                    b.Navigation("ClientContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("OfferGen.Entities.Models.Company", b =>
                {
                    b.OwnsOne("OfferGen.Entities.Records.ComplexValueTypes+Address", "CompanyAddress", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZIPCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("OfferGen.Entities.Records.ComplexValueTypes+ContactInfo", "CompanyContactInfo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContactPerson")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("CompanyAddress")
                        .IsRequired();

                    b.Navigation("CompanyContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("OfferGen.Entities.Models.CompanyRelations.BankAccounts", b =>
                {
                    b.HasOne("OfferGen.Entities.Models.Company", "Company")
                        .WithMany("Accounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OfferGen.Entities.Models.CompanyRelations.BankAccountDetails", "AccountDetails", b1 =>
                        {
                            b1.Property<Guid>("BankAccountsId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BankAccountsId");

                            b1.ToTable("BankAccounts");

                            b1.WithOwner()
                                .HasForeignKey("BankAccountsId");
                        });

                    b.Navigation("AccountDetails")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.CompanyRelations.OfferHeader", b =>
                {
                    b.HasOne("OfferGen.Entities.Models.Company", "Company")
                        .WithOne("OfferHeader")
                        .HasForeignKey("OfferGen.Entities.Models.CompanyRelations.OfferHeader", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OfferGen.Entities.Models.Company", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("OfferHeader")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
